# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskdesc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
